services:
  minecraft-fabric-server:
    image: itzg/minecraft-server
    restart: unless-stopped

    tty: true
    stdin_open: true

    environment:
      EULA: "TRUE"
      TYPE: "${SERVER_TYPE}"
      VERSION: "26.2"
      # SEED: ""
      MEMORY: "4G"
      SIMULATION_DISTANCE: 16
      LOG_IPS: "true"
      # PLUGINS: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
      # MODRINTH_PROJECTS: "viaversion,discordsrv,essentialsx"
      # MODRINTH_ALLOWED_VERSION_TYPE: "beta"
      OPS: "${OPS}"
      MOTD: "${MOTD}"
      ICON: /server-icon.png
      OVERRIDE_ICON: true
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"

    env_file:
      - .env

    volumes:
      - ./data/world:/data
      - ./config:/config
      - ./server-icon.png:/server-icon.png

    labels:
    - "mc-router.host=${SERVER_URL}"

    networks:
      - mc-network


  mc-fabric-backup:
    image: itzg/mc-backup

    depends_on:
      - minecraft-fabric-server

    environment:
      RCON_HOST: "minecraft-fabric-server"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      BACKUP_INTERVAL: "1h"
      PRUNE_BACKUPS_DAYS: 7
      PAUSE_IF_NO_PLAYERS: "true"

    volumes:
      - ./data:/data:ro
      - ./backups:/backups

    networks:
      - mc-network


networks:
  mc-network:
    external: true