services:
  mc-neoforge-server:
    image: itzg/minecraft-server
    container_name: mc-neoforge-server
    restart: unless-stopped

    tty: true
    stdin_open: true

    environment:
      EULA: "TRUE"
      TYPE: "${SERVER_TYPE}"
      VERSION: "26.1.2"
      # SEED: ""

      MODRINTH_PROJECTS: "jei, appleskin, waystones"
      MODRINTH_ALLOWED_VERSION_TYPE: "beta"

      MEMORY: "4G"
      SIMULATION_DISTANCE: 16
      LOG_IPS: "true"
      # TODO: Add MODs here
      OPS: "${OPS}"
      MOTD: "${MOTD}"
      ICON: /server-icon.png
      OVERRIDE_ICON: true
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"

    env_file:
      - .env

    volumes:
      - ./data/world:/data
      - ./config:/config
      - ./server-icon.png:/server-icon.png

    labels:
    - "mc-router.host=${SERVER_URL}"
    - "mc-router.auto-scale-down=true"
    - "mc-router.scale-down-after=2h"

    networks:
      - mc-network


  mc-neoforge-backup:
    image: itzg/mc-backup
    container_name: mc-neoforge-backup
    restart: unless-stopped

    depends_on:
      - mc-neoforge-server

    environment:
      RCON_HOST: "mc-neoforge-server"
      RCON_PASSWORD: "${RCON_PASSWORD}"

      RCON_RETRIES: "-1"
      RCON_RETRY_INTERVAL: "1m"
      PAUSE_IF_NO_PLAYERS: "true"

      BACKUP_METHOD: "restic"
      RESTIC_PASSWORD: "${RESTIC_PASSWORD}"
      RESTIC_REPOSITORY: "/backups"
      BACKUP_INTERVAL: "1h"
      PRUNE_BACKUPS_DAYS: 7

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    volumes:
      - ./data:/data:ro
      - ./backups:/backups

    networks:
      - mc-network


networks:
  mc-network:
    external: true