services:
  minecraft-vanilla-server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: "${SERVER_TYPE}"
      VERSION: "26.1.2"
      # SEED: ""
      MEMORY: "4G"
      SIMULATION_DISTANCE: 16
      LOG_IPS: "true"
      OPS: "${OPS}"
      MOTD: "${MOTD}"
      ICON: /server-icon.png
      OVERRIDE_ICON: true
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
    env_file:
      - .env
    volumes:
      - ./data/world:/data
      - ./config:/config
      - ./server-icon.png:/server-icon.png
    labels:
    - "mc-router.host=${SERVER_URL}"
    - "mc-router.auto-scale-down=true"
    - "mc-router.scale-down-after=2h"
    networks:
      - mc-network

  mc-vanilla-backup:
    image: itzg/mc-backup
    depends_on:
      - minecraft-vanilla-server
    environment:
      RCON_HOST: "minecraft-vanilla-server"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      BACKUP_INTERVAL: "1h"
      PRUNE_BACKUPS_DAYS: 7
      PAUSE_IF_NO_PLAYERS: "true"
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
    networks:
      - mc-network

networks:
  mc-network:
    external: true